fc1_size: 1024
fc2_size: 256
gamma: 0.99
epsilon: 1.0
epsilon_min: 0.01
epsilon_decay: 0.999
learning_rate: 0.0001
memory_size: 10000
batch_size: 128
episodes: 20000
max_steps: 300
environment: Breakout-v4
reward_plateau_threshold: 0.0001
loss_plateau_threshold: 0.00001
plateau_window: 50
use_conv: true
conv1_out_channels: 32
conv1_kernel_size: 8
conv1_stride: 4
conv2_out_channels: 64
conv2_kernel_size: 4
conv2_stride: 2
conv3_out_channels: 64
conv3_kernel_size: 3
conv3_stride: 1
